- name: "bug"
  color: "d73a4a"
- name: "chore"
  color: "ffffff"
- name: "documentation"
  color: "0075ca"
- name: "duplicate"
  color: "cfd3d7"
- name: "in progress"
  color: "ffccd7"
- name: "important"
  color: "fc1423"
- name: "semver:major"
  color: "c10f47"
- name: "semver:minor"
  color: "e4f486"
- name: "semver:patch"
  color: "e8be8b"
- name: "wontfix"
  color: "ffffff"
